### ISSUE TITLE
書籍一覧から詳細ページに遷移時Cannot read property 'volumeInfo'

### ISSUE THREAD

**Issue by ryoma0521** [kooooichi24/BookTock-frontend#17]
問題：
詳細ページに遷移時にCannot read property 'volumeInfo'が出る

状況：
書籍一覧でjavaと検索し、わかりやすいJava入門編をクリックするとCannot read property 'volumeInfo'が出る

解決策案：
BookDetail.vueのLikeタグを以下に変更
`<Like :industryIdentifiers="item.volumeInfo.industryIdentifiers" :book="item"/>`

**Comment by kooooichi24** [comment]
問題が発生している際の、動作環境を教えてください🤔

以下の動作環境では、エラーが発生しませんでした😯
- front branch
  - feature_createLikeClassify_by_furukawa_0717_2

- server branch
  - feature_createLikeClassifyTypeSQL_by_uji_0717

**Comment by ryoma0521** [comment]
ありがとうございます！こちらで対応します。
- front branch
  - feature_issue13_register_new_book_0717
において、書籍が登録されていない本に対して、「いいね」ボタン押下時に書籍データを追加するため、propsで書籍データを渡すよう変更を行いました。
コンフリクトが起きないよう後回しにしていました。

**Comment by kooooichi24** [comment]
これ後で教えて〜〜〜
`<Like :industryIdentifiers="item.volumeInfo.industryIdentifiers" :book="item"/>`
の部分で:bookでLikeコンポーネントにpropsを渡しているけど、Likeコンポーネントでbook propsを利用していなかったので、、
